#!/bin/bash
# Phase 1: generate all TTS clips with /usr/bin/say (Samantha, 175 wpm),
# convert to 44.1kHz stereo 16-bit PCM wav, print measured durations.
set -euo pipefail
export PATH="$HOME/.local/bin:/usr/bin:/bin:$PATH"
FF=/Users/saiaathishkarthik/Desktop/Pactra/node_modules/ffmpeg-static/ffmpeg
FP=/Users/saiaathishkarthik/Desktop/Pactra/node_modules/ffprobe-static/bin/darwin/arm64/ffprobe
DIR=/Users/saiaathishkarthik/Desktop/Pactra/scripts/demo-media
W="$DIR/work"
mkdir -p "$W"
VOICE=Samantha
RATE=175

tts() {
  local name="$1"; local text="$2"
  /usr/bin/say -v "$VOICE" -r "$RATE" -o "$W/$name.aiff" "$text"
  "$FF" -y -v error -i "$W/$name.aiff" -ar 44100 -ac 2 -c:a pcm_s16le "$W/$name.wav"
  local d
  d=$("$FP" -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 "$W/$name.wav")
  echo "$name  $d"
}

# ---- failing.mp4 sections ----
tts fA "Hey everyone, welcome back to the channel. Today I want to tell you about a new productivity app that I have been testing for the past few weeks. It completely changed the way I organize my week, and I think you are going to love it."
tts fB "Before I tell you about it, I should mention that this video is sponsored by Acme."
tts fC "Acme's app is genuinely excellent. It helps you plan your week in under five minutes, and you can share schedules with your whole team. You get a 30-day free trial when you sign up, and it works on every device you own. Use the code PACTRA20 at checkout to get started. Some people expect guaranteed results after a single week, and Acme really does deliver."
tts fD "I also want to mention a few other tools I have been loving lately, starting with a note taking app that syncs everywhere, and a really nice habit tracker that keeps me honest every single day. There is also a podcast app I discovered that summarizes long episodes, which saves me a ton of time on my morning commute. If you enjoyed this video, please leave a like, and let me know in the comments what apps you would like me to try out next. Thanks so much for watching, and I will see you in the next one."
tts fD2 "One more app that surprised me this month is a calendar tool with smart suggestions. It looks at my meetings and quietly finds free windows, which is handy when I need to book time with people in different time zones. I also set up a tiny widget that shows my top three tasks for the day, and I keep it on my home screen so I never lose track of what matters. The best part is that everything works together, so I do not need to copy anything by hand, and my whole week is visible in one place."
tts fD3 "Beyond apps, I have been trying to protect my focus during the day. I put my phone in another room while I do deep work, and I only check messages at set times. It took about a week to get used to it, but now my afternoons feel much calmer, and I finish my to do list earlier than before. If you struggle with distractions, I recommend trying something similar."

# ---- passing.mp4 sections ----
tts pA "Hey everyone, welcome back to the channel. Today I want to tell you about a new productivity app that I have been testing for the past few weeks. It completely changed the way I organize my week, and I think you are going to love it. Let me also share what I have learned about time blocking, and why I think it works so well for people who juggle a lot of projects at once. I have been using this system for about a month now, and my planning routine takes less time than it used to, which leaves me with more energy for the actual work. So let me walk you through the whole setup, step by step, and at the end I will give you all the details you need to try it yourself."
tts pA2 "And if you are new here, I would also point you to the first video in this series, where I break down the entire system from the very beginning."
tts pB "Before I get into the details, I need to mention that this video is sponsored by Acme."
tts pC "Acme's app helps you plan your week in under five minutes, and you can share schedules with your whole team. You get a 30-day free trial when you sign up, and it works on every device you own. Use the code PACTRA20 at checkout to get started. The team ships new features every month, and support responds within a day. I genuinely recommend giving it a try."

# ---- long10.mp4 filler paragraphs (no disclosure terms, no "Acme") ----
tts F1 "I want to spend some time talking about how I structure my mornings. I wake up at the same hour every day, even on weekends, and I start with a short walk outside before I look at any screen. That small routine does more for my mood than any app ever has. After breakfast I sit down and write out the three most important tasks for the day, and I try to finish the hardest one first while my energy is still high. By lunchtime I usually feel like the day is already a success, and the rest of the afternoon becomes a bonus instead of a struggle. I have kept this habit for about two months, and it is the single biggest change to my daily life in years."
tts F2 "When I need to get real work done, I put my phone in a drawer and close every tab that is not part of the task. I also set a timer for fifty minutes and I do not stop until it rings, no matter how tempting it is to check the news. After the timer goes off I take a ten minute break and walk around the room. I found that repeating this cycle four or five times lets me finish in one morning what used to take me two full days. The key is to protect the block from every interruption, including the ones I create myself, because my own habits used to be my biggest distraction."
tts F3 "Lately I have been keeping a single notebook for everything, instead of juggling many different places for my notes. I write down meetings, ideas, and shopping lists on the same pages, and I review the whole notebook every Sunday evening. That weekly review is where the magic happens, because I can see what I planned and what I actually finished. Anything that did not get done gets a decision, either I move it to next week or I drop it for good. My notebook is nothing fancy, just plain paper and a pen, but it works better for me than any digital tool I have tried."
tts F4 "I have also changed the way I consume long form content. Instead of letting my feed choose what I read, I keep a small list of topics I genuinely care about, and I search for those specific things when I have time. When I find a long article or an interview, I read it in two or three short sessions rather than trying to finish it in one sitting. That way I actually remember what I learned, and I can take notes while the ideas are still fresh in my head. It feels slower at first, but the retention is so much better that I never went back to my old habits."
tts F5 "Email used to be the thing that ate my whole day, so I made a rule about it. I only open my inbox twice a day, once in the morning and once in the late afternoon, and I keep my reply folder very small. Everything else stays unread until one of those two windows. At first I was worried I would miss something urgent, but after a few weeks I realized that almost nothing actually needs an answer within the hour. People wait for my reply just fine, and I get to spend the middle of my day on the work that actually moves my projects forward."
tts F6 "Every Friday I do a quick review of the week that just ended. I look at my calendar and my task list, and I ask myself three questions. What went well, what went wrong, and what will I do differently next week. I write the answers on one page and I keep that page visible all weekend. The routine sounds simple, but it changed the way I plan, because I stopped repeating the same mistakes week after week. When Monday comes, I already know exactly what needs my attention, and I do not waste the first hour of the week trying to figure out where to start."
tts F7 "I used to believe that the best way to get more done was to work longer hours, but I have completely changed my mind. I now pay attention to my energy instead of my clock, and I schedule my hardest thinking for the hours when I feel sharpest. For me that is the late morning, so I protect that time and leave meetings for the afternoon. I also stopped skipping lunch, which sounds obvious, but I used to eat at my desk while answering messages. Now I step away for a real break, and I come back with a clear head and better ideas."
tts F8 "A few tools have earned a permanent place on my phone. One is a habit tracker that asks me a single yes or no question every evening, and another is a reading app that keeps my place across all my devices. I also use a simple timer app for my work sessions, though I think the timer matters less than the rule I set for myself. The rule is that I never start a session without knowing exactly what I want to finish by the end of it. When I know the outcome in advance, the session is always better, and I rarely leave a block of time feeling lost."
tts F9 "Most of my projects fail in the planning phase, not because the ideas are bad, but because the next step is unclear. So I started writing down the very next action for every project, and I keep that list at the top of my task manager. When I finish one action, the list tells me the next one, and the project keeps moving without me having to think about it. This sounds like a tiny change, but it removed most of the friction from my work. I no longer stare at a big scary project and wonder where to start, because the next step is always written down and waiting for me."
tts F10 "I have also learned to take breaks seriously. For years I believed that pushing through exhaustion was a sign of discipline, and I was wrong about that. Now I take a short break every ninety minutes, and I use that time to stretch, drink water, and look out the window at something far away. My eyes feel better, my back feels better, and I make fewer mistakes in the afternoon. The funny thing is that I get the same amount of work done in fewer hours, because my focus is stronger when I actually sit down to work."
tts F11 "My commute has become my favorite part of the day, which is a sentence I never thought I would say. I put together a few playlists and a stack of short audio shows, and I listen with one rule, I only save things that I want to hear again. Anything that does not earn a second listen gets deleted, so my library stays small and excellent. By the time I arrive, I have usually learned something useful, and I walk into the office with my mind already warmed up and ready for the first meeting of the day."
tts F12 "The last thing I want to share is the biggest lesson from all of this experimenting. Tools and routines only work when they fit your life, so I always start small and change one thing at a time. When a new habit sticks for two weeks, I add another one, and I drop anything that feels like a fight. Over the past year, this slow approach gave me back a surprising amount of time every single week, and I feel less rushed than I did before. I hope some of these ideas help you the way they helped me, and I would love to hear what works for you."

echo "DONE"
